name: Deploy

on:
  push:
    paths:
      - skillBridgeBackend/prisma/migrations/** # Run this workflow when migrations are updated
    branches:
      - main
  workflow_dispatch: # Allow manual triggering from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Navigate to backend
        working-directory: ./skillBridgeBackend
        run: pwd
      - name: Install dependencies
        working-directory: ./skillBridgeBackend
        run: npm install
      - name: Apply all pending migrations to the database
        working-directory: ./skillBridgeBackend
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
